name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: touch ./Learner/src/main/resources/application.properties

      - run: echo "${{secrets.APPLICATION}}" > ./Learner/src/main/resources/application.properties

      - uses: actions/upload-artifact@v4
        with:
          name: application.properties
          path: ./Learner/src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./Learner/gradlew

      - name: Build with Gradle
        run: |
          cd Learner
          ./gradlew clean bootJar

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          cd Learner/build/libs
          zip -r ../../../deploy.zip *.jar

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22  # v21에서 v22로 업데이트
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: grepp-web
          environment_name: Grepp-web-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300
          use_existing_version_if_available: false
          deployment_timeout: 600  # 10분으로 설정